limit_req_zone $binary_remote_addr zone=rupixexplorer:10m rate=12r/s;

server {
    server_name explorer.rupix.network;

    location / {
        limit_req zone=rupixexplorer burst=24 nodelay;
        proxy_pass http://127.0.0.1:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 30s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/explorer.rupix.network/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/explorer.rupix.network/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = explorer.rupix.network) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name explorer.rupix.network;
    return 404; # managed by Certbot


}