name: Build and upload assets
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Building, ${{ matrix.os }}
    steps:
      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          go build -v -ldflags="-s -w -extldflags=-static" -tags netgo,osusergo -o ./bin/ .
          go build -v -ldflags="-s -w -extldflags=-static" -tags netgo,osusergo -o ./bin/ ./cmd/rupixctl ./cmd/rupixwallet ./cmd/rupixminer
          archive="rupix-${{ github.event.release.tag_name }}-linux.zip"
          zip -r -j "${archive}" ./bin/*
          echo "archive=${archive}" >> $GITHUB_ENV
      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          go build -v -ldflags="-s -w" -o bin/ .
          go build -v -ldflags="-s -w" -o bin/ ./cmd/rupixctl ./cmd/rupixwallet ./cmd/rupixminer
          archive="rupix-${{ github.event.release.tag_name }}-win64.zip"
          powershell "Compress-Archive bin/* \"${archive}\""
          echo "archive=${archive}" >> $GITHUB_ENV
      - name: Build on MacOS
        if: runner.os == 'macOS'
        run: |
          go build -v -ldflags="-s -w" -o ./bin/ .
          go build -v -ldflags="-s -w" -o ./bin/ ./cmd/rupixctl ./cmd/rupixwallet ./cmd/rupixminer
          archive="rupix-${{ github.event.release.tag_name }}-osx.zip"
          zip -r -j "${archive}" ./bin/*
          echo "archive=${archive}" >> $GITHUB_ENV
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.archive }}
